version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: auditorias
      POSTGRES_USER: trejito
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      DATASOURCE_URL: jdbc:postgresql://auditorias:5432/auditorias?createDatabaseIfNotExist=true&serverTimezone=UTC
      DATASOURCE_USERNAME: trejito
      DATASOURCE_PASSWORD: 1234
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      OPENWEATHERMAP_API_KEY: 7ca0086417fee50057b06f637758b88c
      GEONAMES_USERNAME: trejito
      DEBUG: true
    ports:
      - "8082:8082"
    depends_on:
      - postgres

volumes:
  postgres_data:
